export const MARKETPLACES = {
    'GUfCR9mK6azb9vcpsxgXyj7XRPAKJd4KMHTTVvtncGgp': 'MAGICEDEN',
    '3D49QorJyNaL4rcpiynbuS3pRH4Y7EXEM6v6ZGaqfFGK': 'SOLANART',
    'BjaNzGdwRcFYeQGfuLYsc1BbaNRG1yxyWs1hZuGRT8J2': 'EXCHANGEART',
    '4pUQS4Jo2dsfWzt3VgHXy3H6RYnEDd11oWPiaM2rdAPw': 'ALPHAART',
}